---
title: "Project"
author: "Logan Caraco"
date: "2/16/2021"
output: html_document
---

```{r setup, echo = FALSE, warning = FALSE}
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE, fig.align = 'center')
```


```{r, echo = FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(magrittr)
```


```{r Import Data, echo = FALSE}
raw_survey_data <- read.csv("https://www.macalester.edu/~ajohns24/data/pulse_of_the_nation.csv")

names(raw_survey_data) <- c("income", "gender", "age", "party", "trump_approval", "education", "marital", "robots", "climate_change", "transformers", "science_is_honest", "vaccines_are_safe", "books", "ghosts", "fed_sci_budget", "earth_sun", "wise_unwise")

raw_survey_data <- raw_survey_data %>% 
  mutate(climate_change_binary = (climate_change == "Real and Caused by People"))
```


  variable |	survey questions
  ---------+-----------------
  `age` |	What is your age?
  `trump_approval` |	Do you approve, disapprove, or neither approve nor disapprove of how Donald Trump is handling his job as president?
  `marital` |	What is your marital status?

```{r Filtering Functions}
is.known <- function (x) { x != "DK/REF" }
is.voting_age <- function (x) { 18 <= x && x <= 90 }
```

```{r Main Dataset}
marital_trump <- raw_survey_data %>%
  select(age, marital, trump_approval) %>%
  filter(is.known(trump_approval), is.known(marital)) %>% 
  filter(is.finite(age), is.voting_age(age)) %>%
  mutate(approves_trump = endsWith(trump_approval, "Approve")) %>%
  mutate(is_married = marital == "Married")
```

```{r Plotting Functions}
add_predictions <- function (model) {
  marital_trump %>% 
    mutate(log_odds = model$fitted.values) %>% 
    mutate(odds = exp(log_odds)) %>% 
    mutate(probability = odds / (1 + odds))
}

plot_probability <- function(data, ast) {
  ggplot(data, ast) + 
    geom_smooth(se = FALSE) +
    xlim(18, 88)
}
```

``` {r}
approval_model <- glm(approves_trump ~ age * is_married, marital_trump, family = "binomial")
summary(approval_model)$coefficients

approval_predictions <- add_predictions(approval_model)
```

``` {r}
marital_model <- glm(is_married ~ age, marital_trump, family = "binomial")
summary(marital_model)$coefficients

marital_model %>%
  add_predictions %>%
  plot_probability(aes(x = age, y = probability))
```

``` {r}
approval_predictions %>%
  plot_probability(aes(x = age, y = probability, color = is_married))
```

  
```{r}
ggplot(marital_trump, aes(x = age, color = approves_trump)) +
  geom_boxplot() +
  facet_wrap(~is_married, labeller = label_both) +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
confint(approval_model)

approval_predictions %>%
  plot_probability(aes(x = age, y = probability, color = is_married)) +
  geom_jitter()
```


```{r}
age_approval <- glm(approves_trump ~ age, marital_trump, family = "binomial")
summary(age_approval)$coefficients
confint(age_approval)

age_approval %>%
  add_predictions %>%
  plot_probability(aes(x = age, y = probability))
```


